### ISSUE TITLE
Cell coordinate can not be zero-length string

### ISSUE THREAD

**Issue by dr-abadis** [PHPOffice/PHPExcel#177]
Downloaded final version from github but the problem still exists.
I just want to read an xslx file and get this error :  

Exception information:

Message: Cell coordinate can not be zero-length string
Stack trace:
#0 C:\xampp\htdocs\wimax.shabdiznet.com\library\PHPExcel\Reader\Excel2007.php(935): PHPExcel_Cell::coordinateFromString('')
#1 C:\xampp\htdocs\wimax.shabdiznet.com\application\models\Functions.php(30): PHPExcel_Reader_Excel2007->load('C:\xampp\tmp\ph...')
#2 C:\xampp\htdocs\wimax.shabdiznet.com\application\controllers\ImportController.php(56): Application_Model_Functions::Read_Excel('C:\xampp\tmp\ph...')
#3 C:\xampp\htdocs\wimax.shabdiznet.com\library\Zend\Controller\Action.php(516): ImportController->indexAction()
#4 C:\xampp\htdocs\wimax.shabdiznet.com\library\Zend\Controller\Dispatcher\Standard.php(295): Zend_Controller_Action->dispatch('indexAction')
#5 C:\xampp\htdocs\wimax.shabdiznet.com\library\Zend\Controller\Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#6 C:\xampp\htdocs\wimax.shabdiznet.com\library\Zend\Application\Bootstrap\Bootstrap.php(97): Zend_Controller_Front->dispatch()
#7 C:\xampp\htdocs\wimax.shabdiznet.com\library\Zend\Application.php(366): Zend_Application_Bootstrap_Bootstrap->run()
#8 C:\xampp\htdocs\wimax.shabdiznet.com\public\index.php(25): Zend_Application->run()
#9 {main}

**Comment by martenhz** [comment]
I'm sorry for bumping this old ticket, but I noticed it is still open and the 'bug' is still present in the current version of PHPExcel 1.8.0. I've noticed that PHPExcel seems unable to handle 'compressed' xlsx files. The 'normal' xlsx files are working smoothly.

Workaround is to open the 'compressed' xlsx file in Excel or LibreOffice Calc and save the file again as xlsx. LibreOffice Calc will automatically save the xlsx file in a format readable by PHPExcel.

**Comment by qiuhaiyu** [comment]
you definde cell is too short, you can add some cells
like this:

> $cell = array('A1','B1','C1','D1','E1','F1','G1','H1','I1','J1','K1','L1','M1','N1','O1','P1','Q1','R1','S1','T1','U1','V1','W1','X1','Y1','Z1');

**Comment by lpillon** [comment]
@dr-abadis any change on this status? 
I'm getting the same problem with just one type of file.. if I get the file and save again, it'll work fine.
But if I use the normal excel file and try to force the coordinates as the default 'A1', it get my rows as [];
