### ISSUE TITLE
Non-contiguous range in chart

### ISSUE THREAD

**Issue by susseau** [PHPOffice/PHPExcel#253]
I am trying to create chart with non-contiguous data range. In Excel I simply separate ranges with a comma, e.g.

``` text
=('Chart'!$C$2:$C$5,'Chart'!$C$7:$C$10)
```

but when I do this in PHPExcel I get such error:

``` log
Formula Error: Unexpected , (0)
#0 \PEAR\PHPExcel\PHPExcel\Calculation.php(2893): PHPExcel_Calculation->_raiseFormulaError('Formula Error: ...')
#1 \PEAR\PHPExcel\PHPExcel\Calculation.php(2404): PHPExcel_Calculation->_parseFormula(''Technical vs H...', Object(PHPExcel_Cell))
#2 \PEAR\PHPExcel\PHPExcel\Chart\DataSeriesValues.php(288): PHPExcel_Calculation->_calculateFormulaValue('='Technical vs ...', NULL, Object(PHPExcel_Cell))
#3 \PEAR\PHPExcel\PHPExcel\Chart\DataSeries.php(342): PHPExcel_Chart_DataSeriesValues->refresh(Object(PHPExcel_Worksheet), true)
#4 \PEAR\PHPExcel\PHPExcel\Chart\PlotArea.php(121): PHPExcel_Chart_DataSeries->refresh(Object(PHPExcel_Worksheet))
```

Is it even possible to create charts from non-contiguous data? If so - how do I do it?
If not - are you planning to add such feature?

**Comment by ComputerTinker** [comment]
@suseu , @abdulkader87 , and @garethellis36 , I just created PR #650 to fix the issue PHPExcel has with comma separated chart data source values. If you have your own fork of PHPExcel, you can merge the patch, otherwise feel free to download from https://github.com/ComputerTinker/PHPExcel, which is up-to-date with /PHPOffice/PHPExcel but has the new patch applied. Everything worked fine in my tests, but let me know if you run into any issues.
