### ISSUE TITLE
Cell coordinate can not be zero-length string

### ISSUE THREAD

**Issue by ssanders** [PHPOffice/PHPExcel#28]
With commit 55aa7b8d2bfd6610c01f0a8f13d20e22c55f6171, I get the following just opening and saving an existing XLS with PHPExcel...

```
Fatal error: Uncaught exception 'PHPExcel_Exception' with message 'Cell coordinate can not be zero-length string' in ...phpexcel/Classes/PHPExcel/Cell.php:528
Stack trace:
#0 ...phpexcel/Classes/PHPExcel/Cell.php(584): PHPExcel_Cell::coordinateFromString('')
#1 ...phpexcel/Classes/PHPExcel/Writer/Excel2007/Workbook.php(364): PHPExcel_Cell::absoluteCoordinate('')
#2 ...phpexcel/Classes/PHPExcel/Writer/Excel2007/Workbook.php(280): PHPExcel_Writer_Excel2007_Workbook->_writeDefinedNameForAutofilter(Object(PHPExcel_Shared_XMLWriter), Object(PHPExcel_Worksheet), 0)
#3 ...phpexcel/Classes/PHPExcel/Writer/Excel2007/Workbook.php(83): PHPExcel_Writer_Excel2007_Workbook->_writeDefinedNames(Object(PHPExcel_Shared_XMLWriter), Object(PHPExcel))
#4 ...ph in ...phpexcel/Classes/PHPExcel/Cell.php on line 528
```

**Comment by lin-credible** [comment]
+ 1

**Comment by lin-credible** [comment]
＋1
